config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :donations
    resources :target_locations
    resources :transports
    resources :users
    resources :subscribers
    resources :success_stories

    root to: "donations#index"
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :donations, only: [:new, :create, :show, :index, :destroy] do
    collection do
      get :thank_you
      get :my
      get :archive
    end
    resources :transports, only: [:new, :create]
  end

  resources :transports, only: [:index] do
    member do
      get :close
      patch :finish
      delete :cancel
    end
  end

  resources :target_locations, only: [:index]

  resources :subscribers, only: [:new, :create]

  get '/healthcheck', to: 'health_check#index'

  root to: 'pages#landing'
  get '/home', to: 'pages#home'
end

app/models/transport.rb
class Transport < ApplicationRecord
  belongs_to :donation
  belongs_to :transporter, class_name: "User"

  validates :donation, presence: true
  validates :name, presence: true
  validates :email, presence: true,
                    format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates :phone, presence: true
  validates :target_location, presence: true, on: :update
end

app/controllers/admin/transports_controller.rb
module Admin
  class TransportsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Transport.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Transport.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :authenticate_user!

  before_action :find_donation, only: [:new, :create]
  before_action :check_assignability, only: [:new, :create]

  before_action :find_transport, only: [:close, :finish, :cancel]
  before_action :check_finishability, only: [:close, :finish]
  before_action :check_cancelability, only: [:cancel]

  def new
    @transport = @donation.transports.new transporter: current_user,
                                          name: current_user.name,
                                          email: current_user.email,
                                          phone: current_user.phone
  end

  def create
    @transport = @donation.transports.new transport_params
    @transport.transporter = current_user

    if @transport.save
      @donation.assign!

      TransportMailer.transport_taken_on_notification(@transport).deliver_later

      flash[:success] = t('transport.succesfully_assigned')
      redirect_to @donation
    else
      render :new
    end
  end

  def index
    @my_transports = current_user.transports
                                 .includes(:donation, :transporter)
                                 .where(donations: {status: :assigned})
                                 .order('donations.available_to')
    @other_transports = Transport.includes(:donation, :transporter)
                                 .where(donations: {status: :assigned})
                                 .where.not(transporter: current_user)
                                 .order('donations.available_to')
    @available_donations = Donation.available.order(available_to: :asc)
  end

  def close
  end

  def finish
    if @transport.update_attributes transport_params
      @transport.donation.finish!
      redirect_to transports_path
    else
      @donation = @transport.donation
      render :close
    end
  end

  def cancel
    @transport.donation.cancel!
    notify_users_about_cancel
    @transport.destroy
    redirect_to transports_path
  end

  private

  def notify_users_about_cancel
    User.to_be_notified_in_email.each do |user|
      TransportMailer.transport_cancelled_notification(@transport.donation, user).deliver_later
    end
  end

  def find_donation
    @donation = Donation.find params[:donation_id]
  end

  def find_transport
    @transport = Transport.find params[:id]
  end

  def transport_params
    params.require(:transport).permit :name, :email, :phone, :target_location
  end

  def check_assignability
    redirect_to @donation, alert: t("transport.can_not_assign") unless @donation.can_assign?
  end

  def check_finishability
    unless transporter_or_admin && @transport.donation.can_finish?
      redirect_to @transport.donation, alert: t("transport.can_not_finish")
    end
  end

  def check_cancelability
    unless transporter_or_admin && @transport.donation.can_cancel?
      redirect_to @transport.donation, alert: t("transport.can_not_cancel")
    end
  end

  def transporter_or_admin
    @transport.transporter == current_user || current_user.admin?
  end
end

app/views/transports/_form.html.erb
<%= simple_form_for([@donation, @transport]) do |form| %>
  <div class="row">
    <div class="col-md-3 mb-3">
      <%= form.input :name %>
    </div>
    <div class="col-md-6 mb-3">
      <%= form.input :email %>
    </div>
    <div class="col-md-3 mb-3">
      <%= form.input :phone %>
    </div>
  </div>

  <%= form.button :submit, t('transport.submit') %>
<% end %>

app/views/transports/_info.html.erb
<dl class="row">
  <dt class="col-sm-3"><%= Transport.human_attribute_name(:name) %></dt>
  <dd class="col-sm-9"><%= transport.name %></dd>

  <dt class="col-sm-3"><%= Transport.human_attribute_name(:phone) %></dt>
  <dd class="col-sm-9"><%= transport.phone %></dd>

  <dt class="col-sm-3"><%= Transport.human_attribute_name(:target_location) %></dt>
  <dd class="col-sm-9"><%= transport.target_location %></dd>
</dl>

app/views/transports/close.html.erb
<h1><%= t('transport.close') %></h1>

<%= render 'donations/info', donation: @transport.donation %>

<%= simple_form_for([:finish, @transport]) do |form| %>
  <%= form.input :target_location, as: :select, collection: TargetLocation.all.map(&:name) %>

  <%= form.button :submit, t('transport.close') %>
<% end %>

app/views/transports/index.haml
%h2= t '.my_transports'
.row
  - @my_transports.each do |transport|
    - donation = transport.donation
    .col-md-3.col-sm-6
      .panel.panel-default
        .panel-body
          %p
            = "#{t 'donations.cards.food_type'}:"
            = link_to donation.food_type, donation
          %p
            = "#{t 'donations.cards.source_address'}:"
            = link_to donation.source_address, "https://maps.google.com/?q=#{donation.source_address}", target: '_blank'
          %p
            = "#{t 'donations.cards.available_to'}:"
            = l donation.available_to, format: :default
          .text-center
            - if donation.can_cancel?
              = link_to t('donations.cards.cancel'), cancel_transport_path(transport), method: :delete, class: 'btn btn-warning', data: {confirm: t('donations.cards.confirm')}
            - if donation.can_finish?
              = link_to t('donations.cards.close'), close_transport_path(transport), class: 'btn btn-success'

%hr/

%h2= t '.available_donations'
.row
  - @available_donations.each do |donation|
    .col-md-3.col-sm-6
      .panel.panel-default
        .panel-body
          %p
            = "#{t 'donations.cards.food_type'}:"
            = link_to donation.food_type, donation
          %p
            = "#{t 'donations.cards.source_address'}:"
            = link_to donation.source_address, "https://maps.google.com/?q=#{donation.source_address}", target: '_blank'
          %p
            = "#{t 'donations.cards.available'}:"
            = available donation.available_from, donation.available_to
          .text-center
            - if donation.user == current_user
              = link_to t('donations.cards.destroy'), donation_path(donation), method: :delete, class: 'btn btn-danger', data: {confirm: t('donations.cards.confirm')}
            - elsif donation.can_assign?
              = link_to t('donations.cards.transport'), new_donation_transport_path(donation), class: 'btn btn-success'

%hr/

%h2= t '.donations_assigned_to_others'
.row
  - @other_transports.each do |transport|
    - donation = transport.donation
    .col-md-3.col-sm-6
      .panel.panel-default
        .panel-body
          %p
            = "#{t 'donations.cards.food_type'}:"
            = link_to donation.food_type, donation
          %p
            = "#{t 'donations.cards.source_address'}:"
            = link_to donation.source_address, "https://maps.google.com/?q=#{donation.source_address}", target: '_blank'
          %p
            = "#{t 'donations.cards.available'}:"
            = available donation.available_from, donation.available_to
          %p
            = "#{t 'donations.cards.transporter'}:"
            = transport.transporter&.name || t('deleted_user')
          .text-center
            - if current_user.admin?
              - dropdown_id = "transport-dropdown-#{transport.id}"
              .dropdown
                %button.btn.btn-default.dropdown-toggle{"id" => dropdown_id, "aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                  = t('donations.cards.assigned')
                  %span.caret
                %ul.dropdown-menu{"aria-labelledby" => dropdown_id}
                  - if donation.can_cancel?
                    %li= link_to t('donations.cards.cancel'), cancel_transport_path(transport), method: :delete, data: {confirm: t('donations.cards.confirm')}
                  - if donation.can_finish?
                    %li= link_to t('donations.cards.close'), close_transport_path(transport)
            - else
              %span.btn.btn-default= t('donations.cards.assigned')

app/views/transports/new.html.erb
<%= content_for :title, t('.call_to_action') %>
<h1><%= t('transport.create_new') %></h1>

<%= render 'donations/info', donation: @donation %>

<h2><%= Donation.human_attribute_name(:transporter) %></h2>
<%= render 'form' %>