config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :donations
    resources :target_locations
    resources :transports
    resources :users
    resources :subscribers
    resources :success_stories

    root to: "donations#index"
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :donations, only: [:new, :create, :show, :index, :destroy] do
    collection do
      get :thank_you
      get :my
      get :archive
    end
    resources :transports, only: [:new, :create]
  end

  resources :transports, only: [:index] do
    member do
      get :close
      patch :finish
      delete :cancel
    end
  end

  resources :target_locations, only: [:index]

  resources :subscribers, only: [:new, :create]

  get '/healthcheck', to: 'health_check#index'

  root to: 'pages#landing'
  get '/home', to: 'pages#home'
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_nav.haml
%nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        %span.bbm= "#{t('shared.nav.bbm')}:"
        = t('shared.nav.brand')
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if current_user&.donations&.any?
          %li= link_to t('.my_donations'), my_donations_path, class: 'nav-link'
        %li
          = link_to transports_path, class: 'nav-link' do
            = t('.active')
            %span.badge= Donation.available.count
        %li
          = link_to t('.target_locations'), target_locations_path, class: 'nav-link'
        %li= link_to t('.archive'), archive_donations_path, class: 'nav-link'
      = link_to t('.donate'), new_donation_path, class: 'btn btn-success navbar-btn'
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", href: "#", role: "button"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu
              %li= link_to t(".account"), edit_user_registration_path, class: 'nav-link'
              - if current_user.has_invitations_left?
                %li= link_to t(".invite"), new_user_invitation_path, class: 'nav-link'
              - if current_user.admin?
                %li= link_to t(".admin"), admin_root_path, class: 'nav-link'
              %li.divider{role: "separator"}
              %li= link_to t(".log_out"), destroy_user_session_path, method: :delete, class: 'nav-link'

        - else
          %li= link_to t(".sign_in"), new_user_session_path, class: 'nav-link'