config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :donations
    resources :target_locations
    resources :transports
    resources :users
    resources :subscribers
    resources :success_stories

    root to: "donations#index"
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :donations, only: [:new, :create, :show, :index, :destroy] do
    collection do
      get :thank_you
      get :my
      get :archive
    end
    resources :transports, only: [:new, :create]
  end

  resources :transports, only: [:index] do
    member do
      get :close
      patch :finish
      delete :cancel
    end
  end

  resources :target_locations, only: [:index]

  resources :subscribers, only: [:new, :create]

  get '/healthcheck', to: 'health_check#index'

  root to: 'pages#landing'
  get '/home', to: 'pages#home'
end

app/models/donation.rb
class Donation < ApplicationRecord
  has_many :transports
  belongs_to :user

  validates :contact_name, presence: true
  validates :contact_phone, presence: true
  validates :source_name, presence: true
  validates :source_address, presence: true
  validates :food_type, presence: true
  validates :available_from, presence: true
  validates :available_to, presence: true

  validates :quantity, presence: true,
            numericality: { greater_than_or_equal_to: 50 }

  state_machine initial: :reported, attribute: :status do
    event :assign do
      transition :reported => :assigned
    end

    event :cancel do
      transition :assigned => :reported
    end

    event :finish do
      transition :assigned => :transported
    end

    event :miss do
      transition :reported => :missed
    end
  end

  scope :reported, -> { where status: :reported }
  scope :assigned, -> { where status: :assigned }
  scope :active, -> { where Donation.arel_table[:available_to].gt(Time.now) }
  scope :available, -> { reported.active }
  scope :archive, -> { where status: [:transported, :missed] }
end

app/controllers/admin/donations_controller.rb
module Admin
  class DonationsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Donation.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Donation.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

  def index
    @donations = Donation.order(available_from: :desc).all
  end

  def my
    @transports_of_my_donations = Transport.includes(:donation, :transporter)
                                           .where(donations: {status: :assigned, user: current_user})
                                           .order('donations.available_to')
    @my_available_donations = current_user.donations.available.order(available_to: :asc)
  end

  def archive
    @donations = Donation.archive.order(available_from: :desc)
  end

  def show
  end

  def new
    last_donation = current_user.donations.last
    @donation = current_user.donations.new contact_name: current_user.name,
                                           contact_phone: current_user.phone,
                                           source_name: last_donation&.source_name,
                                           source_address: last_donation&.source_address,
                                           available_from: Time.current,
                                           available_to: 2.hours.from_now
  end

  def create
    @donation = current_user.donations.new donation_params

    if @donation.save
      notify_about_creation @donation
      redirect_to thank_you_donations_url
    else
      render :new
    end
  end

  def destroy
    @donation = current_user.donations.find params[:id]

    transports = @donation.transports
    food_type = @donation.food_type
    quantity = @donation.quantity

    @donation.destroy

    notify_about_revocation transports, food_type, quantity
    redirect_to my_donations_path
  end

  private

  def notify_about_creation(donation)
    User.to_be_notified_in_email.each do |user|
      DonationMailer.created_notification(donation, user).deliver_later
    end
  end

  def notify_about_revocation(transports, food_type, quantity)
    transports.each do |transport|
      DonationMailer.revocated_notification(food_type, quantity, transport.transporter).deliver_later
    end
  end

  def set_donation
    @donation = Donation.find params[:id]
  end

  def donation_params
    params.require(:donation).permit(
      :contact_name, :contact_phone,
      :source_name, :source_address,
      :food_type, :quantity,
      :available_from, :available_to,
      :comment, :anonymous,
      :not_perishable, :packaged
    )
  end
end

app/views/donations/_form.html.erb
<%= simple_form_for(donation) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <%= form.input :contact_name %>
    </div>
    <div class="col-md-6">
      <%= form.input :contact_phone %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= form.input :source_name %>
    </div>
    <div class="col-md-6">
      <%= form.input :source_address %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= form.input :food_type %>
    </div>
    <div class="col-md-6">
      <%= form.input :quantity %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= form.input :available_from, as: :string, input_html: { class: 'datetime-picker' } %>
    </div>
    <div class="col-md-6">
      <%= form.input :available_to, as: :string, input_html: { class: 'datetime-picker' } %>
    </div>
  </div>

  <%= form.input :packaged, required: false %>
  <%= form.input :anonymous, required: false %>
  <%= form.input :not_perishable, required: false %>

  <%= form.input :comment %>

  <%= form.button :submit, t('donation.submit') %>
<% end %>

app/views/donations/_info.html.erb
<dl class="row">
  <dt class="col-sm-3"><%= Donation.human_attribute_name(:source_name) %></dt>
  <dd class="col-sm-9"><%= donation.source_name %></dd>

  <dt class="col-sm-3"><%= Donation.human_attribute_name(:source_address) %></dt>
  <dd class="col-sm-9"><%= donation.source_address %></dd>

  <dt class="col-sm-3"><%= Donation.human_attribute_name(:food_type) %></dt>
  <dd class="col-sm-9"><%= donation.food_type %></dd>

  <dt class="col-sm-3"><%= Donation.human_attribute_name(:quantity) %></dt>
  <dd class="col-sm-9"><%= donation.quantity %></dd>

  <dt class="col-sm-3"><%= t '.package' %></dt>
  <dd class="col-sm-9"><%= donation.packaged ? t('.packaged') : t('.not_packaged') %></dd>

  <% unless donation.comment.blank? %>
    <dt class="col-sm-3"><%= Donation.human_attribute_name(:comment) %></dt>
    <dd class="col-sm-9"><%= donation.comment %></dd>
  <% end %>

  <dt class="col-sm-3"><%= Donation.human_attribute_name(:available_from) %></dt>
  <dd class="col-sm-9"><%= l donation.available_from %></dd>

  <dt class="col-sm-3"><%= Donation.human_attribute_name(:available_to) %></dt>
  <dd class="col-sm-9"><%= l donation.available_to %></dd>

  <dt class="col-sm-3"><%= Donation.human_attribute_name(:contact_name) %></dt>
  <dd class="col-sm-9"><%= donation.contact_name %></dd>

  <dt class="col-sm-3"><%= Donation.human_attribute_name(:contact_phone) %></dt>
  <dd class="col-sm-9"><%= donation.contact_phone %></dd>

  <dt class="col-sm-3"><%= Donation.human_attribute_name(:status) %></dt>
  <dd class="col-sm-9"><%= t donation.status, scope: [:donation, :statuses] %></dd>
</dl>

app/views/donations/_table.haml
%table.table
  %thead
    %tr
      %th= Donation.human_attribute_name :available_from
      %th= Donation.human_attribute_name :source_name
      %th= Donation.human_attribute_name :source_address
      %th= Donation.human_attribute_name :quantity
      %th= Donation.human_attribute_name :food_type
      %th= Donation.human_attribute_name :status
      %th{:colspan => "2"}
  %tbody
    - donations.each do |donation|
      %tr
        %td= l donation.available_from
        %td= donation.source_name
        %td= donation.source_address
        %td= donation.quantity
        %td= donation.food_type
        %td= t donation.status, scope: [:donation, :statuses]
        %td= link_to t('.show'), donation
        %td= link_to t('donation.assign'), new_donation_transport_path(donation) if donation.can_assign?

app/views/donations/archive.haml
%h2= t '.title'
= render 'table', donations: @donations

app/views/donations/index.html.erb
<h1>
  <%= t '.title' %>
  <%= link_to t(:create_new, scope: [:donation]), new_donation_path, class: "btn btn-primary pull-right" %>
</h1>

<%= render 'table', donations: @donations %>

<br>

<%= link_to t(:create_new, scope: [:donation]), new_donation_path, class: "btn btn-primary" %>

app/views/donations/my.haml
%h2= t '.my_assigned_donations'
.row
  - @transports_of_my_donations.each do |transport|
    - donation = transport.donation
    .col-md-3.col-sm-6
      .panel.panel-default
        .panel-body
          %p
            = "#{t 'donations.cards.food_type'}:"
            = link_to donation.food_type, donation
          %p
            = "#{t 'donations.cards.source_address'}:"
            = link_to donation.source_address, "https://maps.google.com/?q=#{donation.source_address}", target: '_blank'
          %p
            = "#{t 'donations.cards.available_from'}:"
            = l donation.available_from, format: :default
          %p
            = "#{t 'donations.cards.transporter'}:"
            = transport.transporter&.name || t('deleted_user')
          .text-center
            = link_to t('donations.cards.destroy'), donation_path(donation), method: :delete, class: 'btn btn-danger', data: {confirm: t('donations.cards.confirm')}

%hr/

%h2= t '.my_available_donations'
.row
  - @my_available_donations.each do |donation|
    .col-md-3.col-sm-6
      .panel.panel-default
        .panel-body.active-donation
          %p
            = "#{t 'donations.cards.food_type'}:"
            = link_to donation.food_type, donation
          %p
            = "#{t 'donations.cards.source_address'}:"
            = link_to donation.source_address, "https://maps.google.com/?q=#{donation.source_address}", target: '_blank'
          %p
            = "#{t 'donations.cards.available'}:"
            = available donation.available_from, donation.available_to
          .text-center
            = link_to t('donations.cards.destroy'), donation_path(donation), method: :delete, class: 'btn btn-danger', data: {confirm: t('donations.cards.confirm')}

app/views/donations/new.html.erb
<h1><%= t('donation.create_new') %></h1>

<ul>
  <% t('donation.instructions').each do |line| %>
    <li><%= line %></li>
  <% end %>
</ul>

<%= render 'form', donation: @donation %>

app/views/donations/show.html.erb
<%= render 'info', donation: @donation %>

<% if transport = @donation.transports.first %>
  <h3><%= Donation.human_attribute_name(:transporter) %></h3>
  <%= render 'transports/info', transport: transport %>
<% end %>

<%= link_to t('donation.assign'), new_donation_transport_path(@donation), class: 'btn btn-success' if @donation.can_assign? %>
<%= link_to t('back'), donations_path %>

app/views/donations/thank_you.html.erb
<h1><%= t('donation.thank_you.title') %></h1>

<p><%= t('donation.thank_you.consequence') %></p>
<p><%= t('donation.thank_you.next_step') %></p>